<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class AttributeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('attributes')->delete();

        DB::table('attribute_translations')->delete();

        $now = Carbon::now();

        DB::table('attributes')->insert([
            [
                'id'                  => '1',
                'code'                => 'sku',
                'admin_name'          => 'SKU',
                'type'                => 'text',
                'validation'          => null,
                'position'            => '1',
                'is_required'         => '1',
                'is_unique'           => '1',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                  => '2',
                'code'                => 'name',
                'admin_name'          => 'نام دوره',
                'type'                => 'text',
                'validation'          => null,
                'position'            => '3',
                'is_required'         => '1',
                'is_unique'           => '0',
                'value_per_locale'    => '1',
                'value_per_channel'   => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '1',
            ],
            [
                'id'                  => '3',
                'code'                => 'short_name',
                'admin_name'          => 'نام کوتاه دوره',
                'type'                => 'text',
                'validation'          => null,
                'position'            => '3',
                'is_required'         => '1',
                'is_unique'           => '0',
                'value_per_locale'    => '1',
                'value_per_channel'   => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '4',
                'code'                => 'url_key',
                'admin_name'          => 'نامک',
                'type'                => 'text',
                'validation'          => null,
                'position'            => '4',
                'is_required'         => '1',
                'is_unique'           => '1',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '5',
                'code'                => 'tax_category_id',
                'admin_name'          => 'دسته‌بندی مالیاتی',
                'type'                => 'select',
                'validation'          => null,
                'position'            => '5',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '6',
                'code'                => 'new',
                'admin_name'          => 'جدید',
                'type'                => 'boolean',
                'validation'          => null,
                'position'            => '6',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '7',
                'code'                => 'featured',
                'admin_name'          => 'ویژه',
                'type'                => 'boolean',
                'validation'          => null,
                'position'            => '7',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '8',
                'code'                => 'visible_individually',
                'admin_name'          => 'قابل مشاهده در فروشگاه',
                'type'                => 'boolean',
                'validation'          => null,
                'position'            => '9',
                'is_required'         => '1',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'created_at'          => $now,
                'use_in_flat'         => '1',
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '9',
                'code'                => 'status',
                'admin_name'          => 'وضعیت',
                'type'                => 'boolean',
                'validation'          => null,
                'position'            => '10',
                'is_required'         => '1',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '10',
                'code'                => 'short_description',
                'admin_name'          => 'توضیحات مختصر',
                'type'                => 'textarea',
                'validation'          => null,
                'position'            => '11',
                'is_required'         => '1',
                'is_unique'           => '0',
                'value_per_locale'    => '1',
                'value_per_channel'   => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '11',
                'code'                => 'description',
                'admin_name'          => 'توضیحات',
                'type'                => 'textarea',
                'validation'          => null,
                'position'            => '12',
                'is_required'         => '1',
                'is_unique'           => '0',
                'value_per_locale'    => '1',
                'value_per_channel'   => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '1',
            ], [
                'id'                  => '12',
                'code'                => 'price',
                'admin_name'          => 'قیمت',
                'type'                => 'price',
                'validation'          => 'decimal',
                'position'            => '13',
                'is_required'         => '1',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '1',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '1',
            ], [
                'id'                  => '13',
                'code'                => 'cost',
                'admin_name'          => 'هزینه',
                'type'                => 'price',
                'validation'          => 'decimal',
                'position'            => '14',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '1',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '14',
                'code'                => 'special_price',
                'admin_name'          => 'قیمت ویژه',
                'type'                => 'price',
                'validation'          => 'decimal',
                'position'            => '15',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '15',
                'code'                => 'special_price_from',
                'admin_name'          => 'تاریخ شروع قیمت ویژه',
                'type'                => 'date',
                'validation'          => null,
                'position'            => '16',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '16',
                'code'                => 'special_price_to',
                'admin_name'          => 'تاریخ پایان قیمت ویژه',
                'type'                => 'date',
                'validation'          => null,
                'position'            => '17',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'use_in_flat'         => '1',
                'is_visible_on_front' => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '17',
                'code'                => 'meta_title',
                'admin_name'          => 'توضیحات متا',
                'type'                => 'textarea',
                'validation'          => null,
                'position'            => '18',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '1',
                'value_per_channel'   => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '18',
                'code'                => 'meta_keywords',
                'admin_name'          => 'کلیدواژه‌های متا',
                'type'                => 'textarea',
                'validation'          => null,
                'position'            => '20',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '1',
                'value_per_channel'   => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '19',
                'code'                => 'meta_description',
                'admin_name'          => 'توضیحات متا',
                'type'                => 'textarea',
                'validation'          => null,
                'position'            => '21',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '1',
                'value_per_channel'   => '1',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '1',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '20',
                'code'                => 'guest_checkout',
                'admin_name'          => 'مهمان میتواند خرید کند',
                'type'                => 'boolean',
                'validation'          => null,
                'position'            => '8',
                'is_required'         => '1',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '21',
                'code'                => 'product_number',
                'admin_name'          => 'شماره محصول',
                'type'                => 'text',
                'validation'          => null,
                'position'            => '2',
                'is_required'         => '0',
                'is_unique'           => '1',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '22',
                'code'                => 'teacher_name',
                'admin_name'          => 'نام استاد',
                'type'                => 'text',
                'validation'          => null,
                'position'            => '1',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '1',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '23',
                'code'                => 'teacher_image',
                'admin_name'          => 'تصویر استاد',
                'type'                => 'image',
                'validation'          => null,
                'position'            => '2',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '1',
                'use_in_flat'         => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '24',
                'code'                => 'teacher_bio',
                'admin_name'          => 'درباره استاد',
                'type'                => 'textarea',
                'validation'          => null,
                'position'            => '3',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '1',
                'use_in_flat'         => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '25',
                'code'                => 'completing',
                'admin_name'          => 'در حال تکیمل',
                'type'                => 'boolean',
                'validation'          => null,
                'position'            => '1',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '1',
                'use_in_flat'         => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '26',
                'code'                => 'class_length',
                'admin_name'          => 'مدت زمان',
                'type'                => 'text',
                'validation'          => null,
                'position'            => '2',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '1',
                'use_in_flat'         => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '27',
                'code'                => 'gender',
                'admin_name'          => 'جنسیت',
                'type'                => 'select',
                'validation'          => null,
                'position'            => '3',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '1',
                'use_in_flat'         => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '28',
                'code'                => 'week_days',
                'admin_name'          => 'روزهای هفته',
                'type'                => 'multiselect',
                'validation'          => null,
                'position'            => '4',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '1',
                'use_in_flat'         => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '29',
                'code'                => 'course_type',
                'admin_name'          => 'نوع دوره',
                'type'                => 'select',
                'validation'          => null,
                'position'            => '5',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '1',
                'use_in_flat'         => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '30',
                'code'                => 'location',
                'admin_name'          => 'محل برگزاری',
                'type'                => 'select',
                'validation'          => null,
                'position'            => '2',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '1',
                'use_in_flat'         => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '31',
                'code'                => 'curriculums',
                'admin_name'          => 'سرفصل ها',
                'type'                => 'textarea',
                'validation'          => null,
                'position'            => '2',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '1',
                'use_in_flat'         => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '32',
                'code'                => 'prerequisites',
                'admin_name'          => 'پیش‌نیازها',
                'type'                => 'textarea',
                'validation'          => null,
                'position'            => '2',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '1',
                'use_in_flat'         => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '33',
                'code'                => 'sources',
                'admin_name'          => 'منابع آموزشی',
                'type'                => 'textarea',
                'validation'          => null,
                'position'            => '2',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '1',
                'use_in_flat'         => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '34',
                'code'                => 'future_job',
                'admin_name'          => 'آینده شغلی',
                'type'                => 'textarea',
                'validation'          => null,
                'position'            => '2',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '1',
                'use_in_flat'         => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '35',
                'code'                => 'portfolio',
                'admin_name'          => 'نمونه‌کار فراگیر',
                'type'                => 'gallery',
                'validation'          => null,
                'position'            => '2',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '1',
                'use_in_flat'         => '0',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '36',
                'code'                => 'moodle_id',
                'admin_name'          => 'کد دوره در سامانه آموزش مجازی',
                'type'                => 'text',
                'validation'          => null,
                'position'            => '2',
                'is_required'         => '0',
                'is_unique'           => '1',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
            [
                'id'                  => '37',
                'code'                => 'teacher_id',
                'admin_name'          => 'کاربر استاد',
                'type'                => 'text',
                'validation'          => null,
                'position'            => '3',
                'is_required'         => '0',
                'is_unique'           => '0',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ], [
                'id'                  => '38',
                'code'                => 'spot_id',
                'admin_name'          => 'کد اسپات پلیر',
                'type'                => 'text',
                'validation'          => null,
                'position'            => '3',
                'is_required'         => '0',
                'is_unique'           => '1',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],[
                'id'                  => '39',
                'code'                => 'rouyesh_code',
                'admin_name'          => 'کد کلاس رویش',
                'type'                => 'text',
                'validation'          => null,
                'position'            => '3',
                'is_required'         => '0',
                'is_unique'           => '1',
                'value_per_locale'    => '0',
                'value_per_channel'   => '0',
                'is_filterable'       => '0',
                'is_configurable'     => '0',
                'is_user_defined'     => '0',
                'is_visible_on_front' => '0',
                'use_in_flat'         => '1',
                'created_at'          => $now,
                'updated_at'          => $now,
                'is_comparable'       => '0',
            ],
        ]);

        DB::table('attribute_translations')->insert([
            [
                'id'           => '1',
                'locale'       => 'fa',
                'name'         => 'SKU',
                'attribute_id' => '1',
            ], [
                'id'           => '2',
                'locale'       => 'fa',
                'name'         => 'نام دوره',
                'attribute_id' => '2',
            ], [
                'id'           => '3',
                'locale'       => 'fa',
                'name'         => 'نام کوتاه دوره',
                'attribute_id' => '3',
            ], [
                'id'           => '4',
                'locale'       => 'fa',
                'name'         => 'نامک',
                'attribute_id' => '4',
            ], [
                'id'           => '5',
                'locale'       => 'fa',
                'name'         => 'دسته‌بندی مالیاتی',
                'attribute_id' => '5',
            ], [
                'id'           => '6',
                'locale'       => 'fa',
                'name'         => 'جدید',
                'attribute_id' => '6',
            ], [
                'id'           => '7',
                'locale'       => 'fa',
                'name'         => 'ویژه',
                'attribute_id' => '7',
            ], [
                'id'           => '8',
                'locale'       => 'fa',
                'name'         => 'قابل مشاهده در فروشگاه',
                'attribute_id' => '8',
            ], [
                'id'           => '9',
                'locale'       => 'fa',
                'name'         => 'وضعیت',
                'attribute_id' => '9',
            ], [
                'id'           => '10',
                'locale'       => 'fa',
                'name'         => 'توضیحات مختصر',
                'attribute_id' => '10',
            ], [
                'id'           => '11',
                'locale'       => 'fa',
                'name'         => 'توضیحات',
                'attribute_id' => '11',
            ], [
                'id'           => '12',
                'locale'       => 'fa',
                'name'         => 'قیمت',
                'attribute_id' => '12',
            ], [
                'id'           => '13',
                'locale'       => 'fa',
                'name'         => 'هزینه',
                'attribute_id' => '13',
            ], [
                'id'           => '14',
                'locale'       => 'fa',
                'name'         => 'قیمت ویژه',
                'attribute_id' => '14',
            ], [
                'id'           => '15',
                'locale'       => 'fa',
                'name'         => 'تاریخ شروع قیمت ویژه',
                'attribute_id' => '15',
            ], [
                'id'           => '16',
                'locale'       => 'fa',
                'name'         => 'تاریخ پایان قیمت ویژه',
                'attribute_id' => '16',
            ], [
                'id'           => '17',
                'locale'       => 'fa',
                'name'         => 'عنوان متا',
                'attribute_id' => '17',
            ], [
                'id'           => '18',
                'locale'       => 'fa',
                'name'         => 'کلیدواژه‌های متا',
                'attribute_id' => '18',
            ], [
                'id'           => '19',
                'locale'       => 'fa',
                'name'         => 'توضیحات متا',
                'attribute_id' => '19',
            ], [
                'id'           => '20',
                'locale'       => 'fa',
                'name'         => 'مهمان میتواند خرید کند',
                'attribute_id' => '20',
            ], [
                'id'           => '21',
                'locale'       => 'fa',
                'name'         => 'شماره محصول',
                'attribute_id' => '21',
            ], [
                'id'           => '22',
                'locale'       => 'fa',
                'name'         => 'نام استاد',
                'attribute_id' => '22',
            ], [
                'id'           => '23',
                'locale'       => 'fa',
                'name'         => 'تصویر استاد',
                'attribute_id' => '23',
            ], [
                'id'           => '24',
                'locale'       => 'fa',
                'name'         => 'درباره استاد',
                'attribute_id' => '24',
            ], [
                'id'           => '25',
                'locale'       => 'fa',
                'name'         => 'در حال تکیمل',
                'attribute_id' => '25',
            ], [
                'id'           => '26',
                'locale'       => 'fa',
                'name'         => 'مدت زمان',
                'attribute_id' => '26',
            ], [
                'id'           => '27',
                'locale'       => 'fa',
                'name'         => 'جنسیت',
                'attribute_id' => '27',
            ], [
                'id'           => '28',
                'locale'       => 'fa',
                'name'         => 'روزهای هفته',
                'attribute_id' => '28',
            ], [
                'id'           => '29',
                'locale'       => 'fa',
                'name'         => 'نوع دوره',
                'attribute_id' => '29',
            ], [
                'id'           => '30',
                'locale'       => 'fa',
                'name'         => 'محل برگزاری',
                'attribute_id' => '30',
            ], [
                'id'           => '31',
                'locale'       => 'fa',
                'name'         => 'سرفصل ها',
                'attribute_id' => '31',
            ], [
                'id'           => '32',
                'locale'       => 'fa',
                'name'         => 'پیش‌نیازها',
                'attribute_id' => '32',
            ], [
                'id'           => '33',
                'locale'       => 'fa',
                'name'         => 'منابع آموزشی',
                'attribute_id' => '33',
            ], [
                'id'           => '34',
                'locale'       => 'fa',
                'name'         => 'آینده شغلی',
                'attribute_id' => '34',
            ], [
                'id'           => '35',
                'locale'       => 'fa',
                'name'         => 'نمونه‌کار فراگیر',
                'attribute_id' => '35',
            ], [
                'id'           => '36',
                'locale'       => 'fa',
                'name'         => 'کد دوره در سامانه آموزش مجازی',
                'attribute_id' => '36',
            ], [
                'id'           => '37',
                'locale'       => 'fa',
                'name'         => 'کاربر استاد',
                'attribute_id' => '37',
            ], [
                'id'           => '38',
                'locale'       => 'fa',
                'name'         => 'کد دوره در اسپات پلیر',
                'attribute_id' => '38',
            ],
            [
                'id'           => '39',
                'locale'       => 'fa',
                'name'         => 'کد کلاس در رویش',
                'attribute_id' => '39',
            ]
        ]);
    }
}
