<?php

return [
    [
        'key' => 'sales.paymentmethods.digipay',
        'name' => 'digipay::messages.admin.title',
        'sort' => 10,
        'fields' => [
            [
                'name' => 'title',
                'title' => 'admin::app.admin.system.title',
                'type' => 'text',
                'validation' => 'required',
                'channel_based' => true,
                'locale_based' => true,
            ],
            [
                'name' => 'description',
                'title' => 'admin::app.admin.system.description',
                'type' => 'textarea',
                'channel_based' => true,
                'locale_based' => true,
            ],
            [
                'name' => 'active',
                'title' => 'admin::app.admin.system.status',
                'type' => 'boolean',
                'validation' => 'required',
                'channel_based' => true,
                'locale_based' => false,
            ],
            [
                'name' => 'sandbox',
                'title' => 'digipay::messages.admin.sandbox',
                'type' => 'boolean',
                'info' => 'digipay::messages.admin.sandbox_info',
                'channel_based' => true,
                'locale_based' => false,
            ],
            [
                'name' => 'client_id',
                'title' => 'digipay::messages.admin.client_id',
                'type' => 'text',
                'info' => 'digipay::messages.admin.client_id_info',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => false,
                'depends' => 'active:1',
            ],
            [
                'name' => 'client_secret',
                'title' => 'digipay::messages.admin.client_secret',
                'type' => 'password',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => false,
                'depends' => 'active:1',
            ],
            [
                'name' => 'username',
                'title' => 'digipay::messages.admin.username',
                'type' => 'text',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => false,
                'depends' => 'active:1',
            ],
            [
                'name' => 'password',
                'title' => 'digipay::messages.admin.password',
                'type' => 'password',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => false,
                'depends' => 'active:1',
            ],
            [
                'name' => 'api_version',
                'title' => 'digipay::messages.admin.api_version',
                'type' => 'select',
                'info' => 'digipay::messages.admin.api_version_info',
                'options' => [
                    [
                        'title' => '2022-02-02',
                        'value' => '2022-02-02',
                    ],
                ],
                'channel_based' => true,
                'locale_based' => false,
            ],
            [
                'name' => 'sort',
                'title' => 'admin::app.admin.system.sort_order',
                'type' => 'text',
                'validation' => 'integer|min:0',
            ],
            [
                'name' => 'minimum_amount',
                'title' => 'digipay::messages.admin.minimum_amount',
                'type' => 'text',
                'validation' => 'integer|min:0',
                'channel_based' => true,
                'locale_based' => false,
            ]
        ],
    ],
];
